// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using concesionarioAPI.Config;

#nullable disable

namespace concesionarioAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240821173959_DbCreated")]
    partial class DbCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("concesionarioAPI.Models.Auto.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPuertas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFabricacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TieneEstereo")
                        .HasColumnType("bit");

                    b.Property<string>("TipoCombustible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadPuertas = 4,
                            FechaFabricacion = new DateTime(2020, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            TieneEstereo = true,
                            TipoCombustible = "Gasolina",
                            Transmision = "Automática"
                        },
                        new
                        {
                            Id = 2,
                            CantidadPuertas = 4,
                            FechaFabricacion = new DateTime(2019, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Honda",
                            Modelo = "Civic",
                            TieneEstereo = true,
                            TipoCombustible = "Gasolina",
                            Transmision = "Manual"
                        },
                        new
                        {
                            Id = 3,
                            CantidadPuertas = 4,
                            FechaFabricacion = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Ford",
                            Modelo = "Focus",
                            TieneEstereo = false,
                            TipoCombustible = "Diesel",
                            Transmision = "Automática"
                        },
                        new
                        {
                            Id = 4,
                            CantidadPuertas = 4,
                            FechaFabricacion = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Chevrolet",
                            Modelo = "Cruze",
                            TieneEstereo = true,
                            TipoCombustible = "Gasolina",
                            Transmision = "Automática"
                        },
                        new
                        {
                            Id = 5,
                            CantidadPuertas = 4,
                            FechaFabricacion = new DateTime(2018, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Volkswagen",
                            Modelo = "Golf",
                            TieneEstereo = false,
                            TipoCombustible = "Gasolina",
                            Transmision = "Manual"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
